### ISSUE TITLE
Duplicate entries for headwords

### ISSUE THREAD

**Issue by falko-strenzke** [digitalpalidictionary/dpd-db#11]
While working on the MDict processing, I realized that the MDict [of this release](https://github.com/digitalpalidictionary/digitalpalidictionary/releases/tag/2023-08-01) contains a number of duplicate entries for headwords (i.e. entries that contain HTMl and not "@@@LINK="):

"1st": 
"2nd": 
"3rd": 
"acc": 
"act": 
"agent": 
"arahant": 
"base": 
"care": 
"evamādi": 
"family": 
"go": 
"hare": 
"he": 
"lit": 
"noun": 
"prefix": 
"pulavaka": 
"sad": 
"sandhi": 
"suffix": 
"sādayati": 
"sāriputtamoggalānā": 
"vayabhiññā": 
"ve": 
"vekacaraṃ": 
"verb": 
"yo": 
"āvedhita": 
"√sadh":

**Comment by bdhrs** [comment]
Yes, the duplicate entries are a known bug in the MDict exporter. Is that a complete list or a sample?

**Comment by falko-strenzke** [comment]
Yes, that should be a complete list since it is the output from the readmydict.py tool that goes through all the entries and where I implemented the check for duplicates.

**Comment by bdhrs** [comment]
I see those are a different kind of duplicate entry, where the same headword occurs in different sections of DPD, for example "family" is in Help (green colour) and English-to-Pāḷi (purple).

**Comment by falko-strenzke** [comment]
but as a reminder: "all the entries" here refers to only the headwords (as explained in the initial report above)
