### ISSUE TITLE
don't stop build scripts for user input

### ISSUE THREAD

**Issue by gambhiro** [digitalpalidictionary/dpd-db#17]
Since you are reading a user's custom values from config.ini already, it is strange to stop a build script in the middle to ask for user input.

The expected behavior would be to continue with the default value without prompting.

I was caught by this a handful of times, when downloading a fresh clone or removing config.ini to reset settings, then starting the db build, leaving to do sth else, and when I come back, it halted waiting for me to press enter.

"Enter your GoldenDict directory prompt" here:

[tools/goldendict_path.py#L18](https://github.com/digitalpalidictionary/dpd-db/blob/80d5afc75573c21af5e13b3e06201818eda353a8/tools/goldendict_path.py#L18)

**Comment by Devamitta** [comment]
I think we can change default:
    "golden_dict"    "copy_unzip": "no",
And add if this is yes it will ask for a directory
