### ISSUE TITLE
How to build DPD for Simsapa

### ISSUE THREAD

**Issue by gambhiro** [digitalpalidictionary/dpd-db#20]
I am primarily interested in generating the complete DPD dictionary in SQLite, including the compound breakup and word lookup facilities. Currently I run a migration script on `dpd.db` which adds the .json results in the db.

So perhaps we should limit the scope of #18 to just this?

makedict.sh has the following sequence:

```
inflections/inflections_to_headwords.py
grammar_dict/grammar_dict.py

exporter/exporter.py
exporter/deconstructor_exporter.py

exporter/tpr_exporter.py
```

Questions:

Is the `grammar_dict.py` now obsoleted in favour of the `deconstructor_exporter.py`, or perhaps it does something different?

Is the `deconstructor_exporter.py` dependent on `exporter.py`, or it can be exectuted separately?

The `tpr_exporter.py::generate_sandhi_data()` produces a headword to breakup dict. Is this different from the deconstructor?

**Comment by Devamitta** [comment]
As I am aware
`grammar_dict/grammar_dict.py
exporter/exporter.py
exporter/deconstructor_exporter.py
exporter/tpr_exporter.py`
are independent of each other, but depends on db components from generating_components.sh
again, file [relationship](https://github.com/digitalpalidictionary/dpd-db/blob/fd42cf39e64b371bd1cccf581833f71691404cb9/dps/relationship.md) may help you find out which exact components require for each dictionary.
