### ISSUE TITLE
Feedback link not opening 

### ISSUE THREAD

**Issue by Devamitta** [digitalpalidictionary/dpd-db#25]
In the MDict application on Android, the Feedback link, which has pre-chosen fields, cannot be opened. However, this is not the case in GoldenDict and DictTango.

**Comment by Devamitta** [comment]
This occurs only with words with numbers.
Once I changed lemma_link for lemma_clean it works fine.

**Comment by bdhrs** [comment]
I cannot reproduce, i assume it's now working.
