### ISSUE TITLE
Error: File Not Found - `cst_wordlist.json`

### ISSUE THREAD

**Issue by giahuylhoang** [digitalpalidictionary/dpd-db#30]
I got the following errors when I was trying to rebuild the db from the scratch 

`panic: open shared_data/frequency/cst_wordlist.json: no such file or directory
goroutine 1 [running]:
dpd/go_modules/tools.ReadJsonSliceString({0x104ccf154, 0x27}, {0x104f23da0, 0x0, 0x0})
.../go_modules/tools/json.go:17 +0xf4
dpd/go_modules/deconstructor/importer.makeCstWords()
.../go_modules/deconstructor/importer/unmatched.go:129 +0x74
dpd/go_modules/deconstructor/importer.MakeUnmatched()
.../go_modules/deconstructor/importer/unmatched.go:59 +0x24
dpd/go_modules/deconstructor/importer.DeconImporter()
.../go_modules/deconstructor/importer/importer.go:29 +0xb8
main.init.0()
.../go_modules/deconstructor/main.go:27 +0x70`

looks like there're no file in the shared_data/frequency folder. Could the authors please share these *.json in the source code?

**Comment by Devamitta** [comment]
Please see updated instructions how to build db

https://github.com/digitalpalidictionary/dpd-db/blob/main/docs/build_db.md

**Comment by bdhrs** [comment]
@giahuylhoang please let me know if the error is resolved, as mentioned above, this can be avoided by following the installation instructions [here](https://github.com/digitalpalidictionary/dpd-db/blob/main/docs/build_db.md)
