### ISSUE TITLE
GoldenDict files not working for Koreader, which uses Stardict files

### ISSUE THREAD

**Issue by f0lie** [digitalpalidictionary/dpd-db#32]
I am trying to use the `dpd-goldendict.zip` with Koreader, [that uses the Stardict format](https://github.com/koreader/koreader/wiki/Dictionary-support#how-to-install-a-dictionary).

While the three dictionaries load into Koreader: Digital Pali Dictionary, DPD Deconstructor, and DPD Grammer, looking up Pali words fail. Even common words like "bhikkhu" fails. 

It seems like I am using the wrong file format, given the download description page says that Stardict is supported. But the other files don't seem like they are supposed to be Stardict.

**Comment by bdhrs** [comment]
What device / OS are you using it on? 

There's a lot of JavaScript in DPD to make the buttons and data work, I suspect KoReader cannot handle that.

Perhaps a simple HTML CSS only version might work.

**Comment by f0lie** [comment]
I am using Koreader on Android. I haven't tested Koreader on a Kobo device, but I am assuming that the issue is the same regardless of the device.

**Comment by bdhrs** [comment]
For Android, I personally use DictTango to display a variety of MDict dictionaries. It's freely available from the Play store and F-Droid. Once installed, you can access it via long press from any app.

I tested Koreader on Android and it appears to be the presence or absence of JavaScript that determines whether a StarDict dictionary works or not. If you want, make an issue with Koreader for JavaScript support for StarDict. They have an active community of developers that may be able to help.
